# file: .github/workflows/build_and_release.yaml
# ...
# lots of codes
# ...
build-aseprite:
  name: Build Aseprite
  needs: create-release
  permissions:
    contents: write
  runs-on: ${{ matrix.os }}
  strategy:
      matrix:
        os: windows-latest
